name: 'cyber_risk'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'cyber_risk'

model-paths: ["models"]
seed-paths: ["seeds"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  cyber_risk:
    +materialized: view

seeds:
  cyber_risk:
    assets:
      +column_types:
        criticality_score: INT64
